name: ecom
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.3.0
  path: ^1.8.3
  image_picker: ^1.0.4
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  wave: ^0.2.2
  intl: ^0.20.2
  provider: ^6.1.1
  cached_network_image: ^3.3.0
  flutter_rating_bar: ^4.0.1
  fl_chart: ^0.66.1
  local_auth: ^2.1.7
  flutter_local_notifications: ^16.3.2
  flutter_localizations:
    sdk: flutter

  carousel_slider: ^5.0.0
  
  badges: ^3.1.2
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
